version: '3.8'

services:
  web:
    build: ./lineman
    container_name: web
    command: python3 lineman/views.py
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
    ports: ["80:80", "5000:5000"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: ./train
    container_name: worker
    command: celery --app=train.tasks.celery worker -Q station,speed --loglevel=info -E
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    links:
      - redis

  scheduler:
    build: ./train
    container_name: scheduler
    command: celery beat --app=train.tasks.celery --loglevel=info
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - worker
    links:
      - redis

  listener:
    build: ./central
    container_name: listener
    command: python3 central/events.py
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - LINEMAN_URL=http://172.18.0.3:5000/api/v1/barrier
    depends_on:
      - redis
      - worker
    links:
      - redis
      - web

  redis:
    image: redis:6-alpine
