version: '3.8'

services:
  web:
    build: ./lineman
    container_name: web
    command: python3 lineman/main.py
    volumes:
      - .:/code
      - ./lineman/lineman/barrier_status.db:/lineman/barrier_status.db
    environment:
      - FLASK_DEBUG=1
      - TZ=Europe/Warsaw
    ports:
      - "127.0.0.1:5002:5002"
    networks:
      micro_static:
        ipv4_address: 10.5.0.103

  worker:
    build: ./train
    container_name: worker
    command: celery --app=train.tasks.celery worker -Q station,speed --loglevel=info -E
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - TZ=Europe/Warsaw
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    links:
      - redis
    networks:
      micro_static:
        ipv4_address: 10.5.0.101

  scheduler:
    build: ./train
    container_name: scheduler
    command: celery beat --app=train.tasks.celery --loglevel=info
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - TZ=Europe/Warsaw
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - worker
    links:
      - redis
    networks:
      micro_static:
        ipv4_address: 10.5.0.102

  listener:
    build: ./central
    container_name: listener
    command: python3 central/events.py
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - TZ=Europe/Warsaw
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - LINEMAN_URL=http://10.5.0.103:5002/api/v1/barrier

    depends_on:
      - redis
      - worker
      - web
    links:
      - redis
      - web
    networks:
      micro_static:
        ipv4_address: 10.5.0.100

  redis:
    image: redis:6-alpine
    networks:
      micro_static:
        ipv4_address: 10.5.0.104

networks:
  micro_static:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
